# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prepcheck-backend
spec:
  type: LoadBalancer
  selector:
    app: prepcheck-backend
  ports:
    - port: 80
      targetPort: 5000
