apiVersion: v1
kind: Service
metadata:
  name: prepcheck-frontend
spec:
  type: ClusterIP
  selector:
    app: prepcheck-frontend
  ports:
    - port: 80          # ingress expects 80
      targetPort: 5173  # forward to Vite
