apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prepcheck-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: prepcheck.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prepcheck-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prepcheck-backend
                port:
                  number: 5000
